-- ========================================================
-- Darshan Tours - Supabase PostgreSQL Schema
-- Generated from SQLite Schema (crm/data/darshan.db)
-- ========================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'staff' CHECK (role IN ('admin','manager','finance','staff')),
  branch TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  last_login TEXT,
  left_at TEXT
);

-- Staff History Audit Table
CREATE TABLE IF NOT EXISTS staff_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  performed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  detail TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_staff_history_staff ON staff_history(staff_id);

-- 2. Sessions
CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  expires_at TEXT NOT NULL,
  ip TEXT
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

-- 3. Customers
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  whatsapp TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  date_of_birth TEXT,
  emergency_contact TEXT,
  source TEXT,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);

-- 4. Branches
CREATE TABLE IF NOT EXISTS branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT,
  address TEXT,
  phone TEXT,
  active INTEGER NOT NULL DEFAULT 1
);

-- 5. Vehicle Categories
CREATE TABLE IF NOT EXISTS vehicle_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'bike' CHECK (kind IN ('bike','scooter','car','van')),
  icon TEXT,
  image TEXT,
  short_desc TEXT,
  description TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0
);

-- 6. Vehicles
CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  model TEXT NOT NULL,
  year INTEGER,
  category_id BIGINT REFERENCES vehicle_categories(id) ON DELETE SET NULL,
  branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  registration_no TEXT,
  cc INTEGER,
  fuel_type TEXT NOT NULL DEFAULT 'Petrol',
  transmission TEXT NOT NULL DEFAULT 'Manual',
  seats INTEGER NOT NULL DEFAULT 2,
  mileage TEXT,
  included_km INTEGER NOT NULL DEFAULT 100,
  extra_km_rate DOUBLE PRECISION NOT NULL DEFAULT 8,
  rate_12h DOUBLE PRECISION NOT NULL DEFAULT 0,
  rate_24h DOUBLE PRECISION NOT NULL DEFAULT 0,
  hourly_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  weekend_rate_24h DOUBLE PRECISION,
  deposit DOUBLE PRECISION NOT NULL DEFAULT 0,
  late_fee_per_hour DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_units INTEGER NOT NULL DEFAULT 1,
  description TEXT,
  terms TEXT,
  status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available','booked','maintenance','archived')),
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_vehicles_category ON vehicles(category_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status);

-- 7. Vehicle Photos
CREATE TABLE IF NOT EXISTS vehicle_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  is_primary INTEGER NOT NULL DEFAULT 0,
  sort INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_vehicle_photos_vehicle ON vehicle_photos(vehicle_id);

-- 8. Pricing Rules
CREATE TABLE IF NOT EXISTS pricing_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES vehicle_categories(id) ON DELETE CASCADE,
  day_type TEXT NOT NULL DEFAULT 'weekend' CHECK (day_type IN ('weekend','long_weekend','holiday','festival','peak','off_season')),
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  rate_24h DOUBLE PRECISION,
  rate_12h DOUBLE PRECISION,
  deposit DOUBLE PRECISION,
  included_km INTEGER,
  extra_km_rate DOUBLE PRECISION,
  min_days INTEGER NOT NULL DEFAULT 1,
  priority INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_pricing_rules_dates ON pricing_rules(start_date, end_date);

-- 9. Availability Blocks
CREATE TABLE IF NOT EXISTS availability_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  starts_at TEXT NOT NULL,
  ends_at TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT 'booked' CHECK (reason IN ('booked','maintenance','manual_block')),
  booking_id BIGINT,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_availability_vehicle ON availability_blocks(vehicle_id, starts_at, ends_at);

-- 10. Terms Versions
CREATE TABLE IF NOT EXISTS terms_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version INTEGER UNIQUE NOT NULL,
  content TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 11. Enquiries
CREATE TABLE IF NOT EXISTS enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_no TEXT UNIQUE NOT NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  category_id BIGINT REFERENCES vehicle_categories(id) ON DELETE SET NULL,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE SET NULL,
  pickup_date TEXT,
  return_date TEXT,
  pickup_time TEXT,
  return_time TEXT,
  location TEXT,
  budget_min DOUBLE PRECISION,
  budget_max DOUBLE PRECISION,
  passengers INTEGER,
  name TEXT,
  phone TEXT,
  email TEXT,
  source TEXT NOT NULL DEFAULT 'Website',
  assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
  stage TEXT NOT NULL DEFAULT 'New',
  notes TEXT,
  data TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'submitted',
  draft_token TEXT UNIQUE,
  submitted_at TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_enquiries_phone ON enquiries(phone);
CREATE INDEX IF NOT EXISTS idx_enquiries_stage ON enquiries(stage);

-- 12. Enquiry History
CREATE TABLE IF NOT EXISTS enquiry_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id BIGINT NOT NULL REFERENCES enquiries(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  detail TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 13. Bookings
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_no TEXT UNIQUE NOT NULL,
  enquiry_id BIGINT REFERENCES enquiries(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE SET NULL,
  branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  pickup_at TEXT NOT NULL,
  return_at TEXT NOT NULL,
  actual_pickup_at TEXT,
  actual_return_at TEXT,
  after_hours INTEGER NOT NULL DEFAULT 0,
  after_hours_approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'Draft',
  base_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  surcharge_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  extra_hours_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  gst_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  discount_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  deposit_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  other_fees_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  extra_km_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  late_fee_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  damage_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  paid_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  included_km INTEGER NOT NULL DEFAULT 0,
  start_odometer DOUBLE PRECISION,
  end_odometer DOUBLE PRECISION,
  manager_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  terms_version_id BIGINT REFERENCES terms_versions(id) ON DELETE SET NULL,
  terms_accepted_at TEXT,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_bookings_vehicle ON bookings(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_bookings_customer ON bookings(customer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_pickup ON bookings(pickup_at, return_at);

-- 14. Booking History
CREATE TABLE IF NOT EXISTS booking_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  detail TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_booking_history_booking ON booking_history(booking_id);

-- 15. Customer Documents
CREATE TABLE IF NOT EXISTS customer_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('licence','govt_id','address_proof','photo','other')),
  number TEXT,
  expiry_date TEXT,
  file_path TEXT NOT NULL,
  verified INTEGER NOT NULL DEFAULT 0,
  verified_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_customer_documents_customer ON customer_documents(customer_id);

-- 16. Inspections
CREATE TABLE IF NOT EXISTS inspections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('handover','return')),
  employee_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  odometer DOUBLE PRECISION,
  fuel_level TEXT,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_inspections_booking ON inspections(booking_id);

-- 17. Inspection Photos
CREATE TABLE IF NOT EXISTS inspection_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inspection_id BIGINT NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
  side TEXT NOT NULL CHECK (side IN ('front','rear','left','right','odometer','fuel','damage','customer')),
  url TEXT NOT NULL,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 18. Damage Reports
CREATE TABLE IF NOT EXISTS damage_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  inspection_id BIGINT REFERENCES inspections(id) ON DELETE SET NULL,
  description TEXT NOT NULL,
  charge_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 19. Manual Adjustments
CREATE TABLE IF NOT EXISTS manual_adjustments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('late_fee_waiver','late_fee_change','price_override','discount','damage_charge','other')),
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  reason TEXT NOT NULL,
  employee_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_adjustments_booking ON manual_adjustments(booking_id);

-- 20. Payments
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_no TEXT UNIQUE NOT NULL,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  amount DOUBLE PRECISION NOT NULL,
  kind TEXT NOT NULL DEFAULT 'advance' CHECK (kind IN ('advance','full','deposit','extra_charge')),
  method TEXT,
  gateway_ref TEXT,
  due_date TEXT,
  paid_at TEXT,
  status TEXT NOT NULL DEFAULT 'Pending',
  notes TEXT,
  receipt_no TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS idx_payments_booking ON payments(booking_id);

-- 21. Refunds
CREATE TABLE IF NOT EXISTS refunds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  refund_no TEXT UNIQUE NOT NULL,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  payment_id BIGINT REFERENCES payments(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  reason TEXT NOT NULL,
  requested_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  approved_amount DOUBLE PRECISION,
  status TEXT NOT NULL DEFAULT 'Requested',
  method TEXT,
  transaction_ref TEXT,
  admin_notes TEXT,
  requested_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  approved_at TEXT,
  completed_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_refunds_booking ON refunds(booking_id);

-- 22. Invoices
CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no TEXT UNIQUE NOT NULL,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  subtotal DOUBLE PRECISION NOT NULL DEFAULT 0,
  tax_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
  discount DOUBLE PRECISION NOT NULL DEFAULT 0,
  total DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 23. Problem Tickets
CREATE TABLE IF NOT EXISTS problem_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_no TEXT UNIQUE NOT NULL,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  category TEXT NOT NULL DEFAULT 'other' CHECK (category IN ('breakdown','tyre','battery','engine','accident','existing_damage','fuel','document','misuse','other')),
  description TEXT NOT NULL,
  media TEXT NOT NULL DEFAULT '[]',
  location TEXT,
  status TEXT NOT NULL DEFAULT 'Open',
  assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
  replacement_vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE SET NULL,
  resolution_notes TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  resolved_at TEXT
);

-- 24. Maintenance Records
CREATE TABLE IF NOT EXISTS maintenance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
  reason TEXT NOT NULL,
  starts_at TEXT NOT NULL,
  ends_at TEXT,
  cost DOUBLE PRECISION,
  notes TEXT,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 25. Tasks
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  assignee_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  priority TEXT NOT NULL DEFAULT 'Normal',
  due_date TEXT,
  status TEXT NOT NULL DEFAULT 'Not started',
  checklist TEXT NOT NULL DEFAULT '[]',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  completed_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_tasks_booking ON tasks(booking_id);

-- 26. Messages
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_id BIGINT REFERENCES enquiries(id) ON DELETE SET NULL,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  channel TEXT NOT NULL,
  to_address TEXT,
  subject TEXT,
  content TEXT,
  status TEXT NOT NULL DEFAULT 'sent',
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 27. Message Templates
CREATE TABLE IF NOT EXISTS message_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT 'whatsapp',
  subject TEXT,
  body TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1
);

-- 28. Notifications
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  enquiry_id BIGINT REFERENCES enquiries(id) ON DELETE SET NULL,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  body TEXT,
  read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 29. Documents
CREATE TABLE IF NOT EXISTS documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id BIGINT NOT NULL,
  kind TEXT,
  name TEXT NOT NULL,
  path TEXT,
  size BIGINT,
  uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 30. Feedback
CREATE TABLE IF NOT EXISTS feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  rating INTEGER,
  review TEXT,
  is_public INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 31. Testimonials
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  vehicle TEXT,
  location TEXT,
  rating INTEGER NOT NULL DEFAULT 5,
  quote TEXT NOT NULL,
  image TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 32. Gallery
CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  image TEXT NOT NULL,
  category TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0
);

-- 33. Blog Posts
CREATE TABLE IF NOT EXISTS blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT NOT NULL,
  cover TEXT,
  author TEXT,
  published INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 34. FAQs
CREATE TABLE IF NOT EXISTS faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  sort INTEGER NOT NULL DEFAULT 0
);

-- 35. OTP Codes
CREATE TABLE IF NOT EXISTS otp_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target TEXT NOT NULL,
  purpose TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used INTEGER NOT NULL DEFAULT 0,
  attempts INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 36. Customer Sessions
CREATE TABLE IF NOT EXISTS customer_sessions (
  token TEXT PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  target TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_customer_sessions_customer ON customer_sessions(customer_id);

-- 37. Activity Logs
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id BIGINT,
  detail TEXT,
  ip TEXT,
  created_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);

-- 38. Settings
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
);
