-- Phase 1: make Supabase the single source of truth.
--
-- Run this BEFORE deploying the code that removes the SQLite mirror.
-- It is idempotent and safe to re-run.

-- ---------------------------------------------------------------------------
-- 1. Repair the identity sequences.
--
-- The old sync pushed ids generated by SQLite's AUTOINCREMENT explicitly into
-- Postgres BIGSERIAL columns. An explicit id does NOT advance the underlying
-- sequence, so every sequence is still sitting near 1 while rows exist at much
-- higher ids. The first native INSERT that omits `id` therefore collides with an
-- existing row: "duplicate key value violates unique constraint".
--
-- This walks every sequence-backed id column and moves the sequence past the
-- highest id currently present.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  rec RECORD;
  seq_name TEXT;
  max_id BIGINT;
BEGIN
  FOR rec IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.tables t
      ON t.table_name = c.table_name AND t.table_schema = c.table_schema
    WHERE c.table_schema = 'public'
      AND c.column_name = 'id'
      AND t.table_type = 'BASE TABLE'
  LOOP
    seq_name := pg_get_serial_sequence('public.' || quote_ident(rec.table_name), 'id');
    IF seq_name IS NOT NULL THEN
      EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM public.%I', rec.table_name) INTO max_id;
      PERFORM setval(seq_name, GREATEST(max_id, 1), max_id > 0);
      RAISE NOTICE 'sequence % set to %', seq_name, GREATEST(max_id, 1);
    END IF;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Columns the application writes but the schema never had.
--
-- supabase-sync.ts stripped these before every write and swallowed the error, so
-- UPI references and payment breakdowns were silently discarded.
-- ---------------------------------------------------------------------------
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS breakdown_json TEXT;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS upi_id TEXT;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS vpa TEXT;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS bank_ref_no TEXT;

-- The web fallback writes kind='online', which the CHECK constraint rejects; the
-- insert failed and the error was swallowed, so those payments were never recorded.
ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_kind_check;
ALTER TABLE public.payments
  ADD CONSTRAINT payments_kind_check
  CHECK (kind IN ('advance', 'full', 'deposit', 'extra_charge', 'online', 'refund'));

-- ---------------------------------------------------------------------------
-- 3. Atomic money accumulators.
--
-- `paid_amount = paid_amount + x` was a read-modify-write against a per-lambda
-- SQLite copy. Two concurrent payments lost one of the increments. Doing the
-- arithmetic inside Postgres makes it atomic.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.increment_booking_paid(p_booking_id BIGINT, p_amount NUMERIC)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE
  new_total NUMERIC;
BEGIN
  UPDATE public.bookings
     SET paid_amount = COALESCE(paid_amount, 0) + p_amount,
         updated_at  = NOW()
   WHERE id = p_booking_id
   RETURNING paid_amount INTO new_total;

  RETURN new_total;
END $$;

CREATE OR REPLACE FUNCTION public.increment_booking_total(p_booking_id BIGINT, p_amount NUMERIC)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE
  new_total NUMERIC;
BEGIN
  UPDATE public.bookings
     SET total_amount = COALESCE(total_amount, 0) + p_amount,
         updated_at   = NOW()
   WHERE id = p_booking_id
   RETURNING total_amount INTO new_total;

  RETURN new_total;
END $$;

-- ---------------------------------------------------------------------------
-- 4. Indexes for the hot lookup paths.
--
-- Every one of these backs a query that currently runs on every page load.
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_bookings_booking_no      ON public.bookings (booking_no);
CREATE INDEX IF NOT EXISTS idx_bookings_customer_id     ON public.bookings (customer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_vehicle_status  ON public.bookings (vehicle_id, status);
CREATE INDEX IF NOT EXISTS idx_bookings_created_at      ON public.bookings (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_booking_id      ON public.payments (booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_rzp_payment_id  ON public.payments (razorpay_payment_id);
CREATE INDEX IF NOT EXISTS idx_customers_phone          ON public.customers (phone);
CREATE INDEX IF NOT EXISTS idx_customer_docs_customer   ON public.customer_documents (customer_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_active          ON public.vehicles (active);
CREATE INDEX IF NOT EXISTS idx_vehicle_photos_vehicle   ON public.vehicle_photos (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_sessions_token           ON public.sessions (token);
CREATE INDEX IF NOT EXISTS idx_customer_sessions_token  ON public.customer_sessions (token);
CREATE INDEX IF NOT EXISTS idx_otp_codes_target         ON public.otp_codes (target, created_at DESC);

-- Webhook idempotency depends on this being unique.
CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_events_event_id
  ON public.payment_events (event_id)
  WHERE event_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 5. Row Level Security.
--
-- There were no policies at all. If RLS is disabled, the publishable/anon key is
-- a full read/write credential on customers, bookings, payments and ID documents.
--
-- Both apps talk to Postgres with the SERVICE ROLE key, which bypasses RLS, so
-- enabling it does not break them. What it does is make the anon key harmless if
-- it ever leaks.
--
-- Deliberately deny-by-default: enabling RLS with no policy denies all non-service
-- access. Add narrower policies later if the browser ever needs direct reads.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users', 'branches', 'vehicle_categories', 'vehicles', 'vehicle_photos',
    'pricing_rules', 'availability_blocks', 'terms_versions', 'customers',
    'enquiries', 'enquiry_history', 'bookings', 'booking_history',
    'customer_documents', 'inspections', 'inspection_photos', 'damage_reports',
    'manual_adjustments', 'payments', 'payment_events', 'refunds', 'invoices',
    'problem_tickets', 'maintenance_records', 'tasks', 'messages',
    'message_templates', 'notifications', 'documents', 'feedback',
    'testimonials', 'gallery', 'blog_posts', 'faqs', 'otp_codes', 'sessions',
    'customer_sessions', 'activity_logs', 'settings', 'staff_history'
  ]
  LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    END IF;
  END LOOP;
END $$;

-- Public website content is safe to expose read-only to the anon key.
-- Everything else stays deny-by-default.
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['vehicles', 'vehicle_categories', 'vehicle_photos', 'testimonials', 'gallery', 'blog_posts', 'faqs', 'branches']
  LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', 'anon_read_' || t, t);
      EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO anon USING (true)', 'anon_read_' || t, t);
    END IF;
  END LOOP;
END $$;
